namespace: app
replicaCount: 1

serviceAccount:
  name: "developer"

image:
  pullPolicy: IfNotPresent
  tag: "vwassa/ktor_app"
  registry: "docker.io"
  secret:
    name: dockerpub

resources: 
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 400Mi

service:
  type: LoadBalancer
  port: 8080


